language: node_js
node_js:
  - "node"

before_install:
  - npm install -g npm@4.3.0

install:
  - npm install

before_script:
  - npm install -g gulp

script:
  - gulp build

notifications:
  email: false
